spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cl6-2.cdqf0gxh6nhf.ap-northeast-2.rds.amazonaws.com/sampledb4?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 12345678

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
      location:

jackson:
  serialization:
    fail-on-empty-beans=false:
#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG

server:
  servlet:
    context-path: /


SECRET_KEY : hello

cloud:
  aws:
    credentials:
      accessKey:       # AWS IAM AccessKey 적기
      secretKey:    # AWS IAM SecretKey 적기
    s3:
      bucket: cl6-2    # ex) marryting-gyunny
      dir: /image # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false